[package]
name = "jeditr-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.1"
pollster = "0.4.0"
uuid = { version = "1.17.0", features = ["v4"] }
wgpu = "25.0.2"
winit = "0.30.11"
